# 파일 규격 버전
version: "3"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services: # 첫번째 db, 두번째 server, 
  # 서비스 명
  db:
    # 사용할 이미지
    image: mysql
    # 컨테이너 이름 설정
    container_name: db
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "3306:3306"
    # -e 옵션 
    environment: 
      # MYSQL 패스워드 설정 옵션
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSOWRD: "1111"
    # 명령어 실행 (한글 인코딩 관련)
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      # -v 옵션 (다렉토리 마운트 설정) (호스트와 컨테이너 디렉토리 연결 (실시간 양방향 반영))
      - C:/works/DOCKER_WEB/data:/var/lib/mysql
    networks:
      - web-net
  server:
    container_name: server
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - C:/works/DOCKER_WEB/server:/app/
    networks:
      - web-net
    depends_on: #순서를 정해줌. db 컨테이너가 생성되고 server를 후순위로 생성하겠다
      - db
networks:
  web-net:
    driver: bridge